language: python
python:
  - 2.7
  - 3.7
  
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no 
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION nose lapack compilers netcdf4 netcdf-fortran xarray scipy matplotlib
  - git clone --branch=master --depth=100 --quiet git://github.com/clawpack/clawpack
  - cd clawpack
  - git submodule init
  - git submodule update -j 6
  - rm -rf geoclaw
  - ln -s ../ geoclaw
  
install:
  - conda activate test-env
  - export PYTHONPATH=${PWD}:$PYTHONPATH
  - export CLAW=${PWD}
  - export FC=gfortran
  - export NETCDF4_DIR=$HOME/miniconda
  - export LIB_PATHS=$HOME/miniconda/lib

before_script:
  # Print CPU info for debugging purposes:
  - cat /proc/cpuinfo
  - python -c "import numpy; print(numpy.__version__)"
  - gfortran -v
  - echo "PYTHONPATH="$PYTHONPATH
  - echo "CLAW="$CLAW
  - echo "FC="$FC
  - echo "NETCDF4_DIR="$NETCDF4_DIR
  - echo "LIB_PATHS="$LIB_PATHS
  - which $FC 
script:
  - cd $CLAW/geoclaw
  - conda activate test-env
  - nosetests -sv

after_failure:
 - for failed_test_path in *_output ; do cat $failed_test_path/run_output.txt ; cat $failed_test_path/error_output.txt ; done
  
notifications:
  email: false
