# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Checkout clawpack
      uses: actions/checkout@v4
      with:
        repository: climateimpactlab/clawpack
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gfortran liblapack-dev libnetcdf-dev libnetcdff-dev
        python -m pip install --upgrade pip
        pip install flake8 pytest
    - name: Setup clawpack super repository
      run: |
        git submodule init
        git submodule update
        pip install --user -e .
    - name: Setup geoclaw
      run: |
        cd geoclaw
        git fetch origin pull/${{ github.event.pull_request.number }}/head:pr
        git checkout pr
    - name: Test with pytest
      run: |
        cd geoclaw
        pytest
